# 1、pandas 映射
常用将字符转化为数字,如果有多个字符，未填写映射关系的将变为 NAN

In [2]:
# 使用map函数映射
import pandas as pd
df = pd.DataFrame([
            ['green', 'M', 10.1, 'class1'], 
            ['red', 'L', 13.5, 'class2'], 
            ['blue', 'XL', 15.3, 'class1']])
print(df) 
df.columns = ['color', 'size', 'prize', 'class label']
 
size_mapping = {
           'XL': 3,
           'L': 2,
           'M': 1}
df['size'] = df['size'].map(size_mapping)
 
class_mapping = {label:idx for idx,label in enumerate(set(df['class label']))}
df['class label'] = df['class label'].map(class_mapping)
df

       0   1     2       3
0  green   M  10.1  class1
1    red   L  13.5  class2
2   blue  XL  15.3  class1


color  size  prize  class label
0  green     1   10.1            0
1    red     2   13.5            1
2   blue     3   15.3            0

# 2、pandas独热编码

### 对所有的数据

In [3]:
# 对所有的数据
df = pd.DataFrame([  
            ['green' , 'A'],   
            ['red'   , 'B'],   
            ['blue'  , 'A']])  

print(df)
df.columns = ['color',  'class'] 
df = pd.get_dummies(df) 
print(df)

       0  1
0  green  A
1    red  B
2   blue  A
   color_blue  color_green  color_red  class_A  class_B
0           0            1          0        1        0
1           0            0          1        0        1
2           1            0          0        1        0


### 对多列数据（数字型需要转化为字符串）

In [21]:
# 对某一列数据
df = pd.DataFrame([  
            ['green' , 'A', 1],   
            ['red'   , 'B', 2],   
            ['blue'  , 'B', 3]], columns = ['color', 'class', 'number']) 
print(df.dtypes)
df["number_string"] = df["number"].astype("str")
pd.get_dummies(df)

color     object
class     object
number     int64
dtype: object


number  color_blue  color_green  color_red  class_A  class_B  \
0       1           0            1          0        1        0   
1       2           0            0          1        0        1   
2       3           1            0          0        0        1   

   number_string_1  number_string_2  number_string_3  
0                1                0                0  
1                0                1                0  
2                0                0                1

In [5]:
# 将编码的数据合并到原数据
df = df.join(pd.get_dummies(df.color))
df

color class  blue  green  red
0  green     A     0      1    0
1    red     B     0      0    1
2   blue     A     1      0    0

# 3、使用sklearn

In [6]:
df = pd.DataFrame([  
            ['green' , 'A'],   
            ['red'   , 'B'],   
            ['blue'  , 'A']], columns = ['color', 'class']) 

from sklearn.feature_extraction import DictVectorizer
dict_vec = DictVectorizer(sparse=False)# #sparse=False意思是不产生稀疏矩阵
X_train = dict_vec.fit_transform(df.to_dict(orient='record'))
# X_test = dict_vec.transform(X_test.to_dict(orient='record'))
print(dict_vec.feature_names_)#查看转换后的列名，原字段有几种，就会产生几列
print(X_train,type(X_train))#查看转换后的训练集

['class=A', 'class=B', 'color=blue', 'color=green', 'color=red']
[[1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0.]] <class 'numpy.ndarray'>


In [7]:
df

color class
0  green     A
1    red     B
2   blue     A